window.LESSONS = {

// ══════════════════════════════════════════════════════
//  PYTHON  — 7 lessons
// ══════════════════════════════════════════════════════
python: [
  {
    id:"py1", title:"Hello, World!", subtitle:"Your very first Python program",
    intro:"Python is one of the most beginner-friendly languages ever created. It reads almost like plain English. Every coder starts here — printing text to the screen.",
    concepts:[
      {icon:"🐍",title:"Python",   desc:"A readable, high-level language used in AI, data science, and web development."},
      {icon:"📣",title:"print()",  desc:"The most fundamental command — displays text or values on screen."},
      {icon:"💬",title:"String",   desc:"Text data, always wrapped in quotes: 'hello' or \"hello\"."},
      {icon:"#", title:"Comment",  desc:"A line starting with # that Python ignores. Use it to leave notes."},
    ],
    filename:"hello.py",
    codeLines:[
      "# Your very first Python program!",
      'print("Hello, World!")',
      'print("Welcome to CodePath!")',
      "",
      "# Print numbers too",
      "print(42)",
      "print(3.14)",
      "",
      "# Math right inside print",
      "print(10 + 5)",
      "print(100 - 37)",
    ],
    breakdown:[
      {token:"# Your very first…",    note:"A <b>comment</b> — starts with #. Python completely ignores this line."},
      {token:'print("Hello, World!")',note:"<b>print()</b> is a built-in function. Whatever is inside the parentheses gets displayed."},
      {token:'"Hello, World!"',       note:"This is a <b>string</b> — text wrapped in double quotes. Single quotes work too."},
      {token:"print(42)",             note:"Numbers don't need quotes. Python knows 42 is a number, not text."},
      {token:"print(10 + 5)",         note:"Python evaluates the math first, then prints the result (15)."},
    ],
    runnable:true,
    starterCode:'# Edit and run!\nprint("Hello, World!")\nprint("My name is ___")',
    challenges:[
      {type:"coding",title:"Print your name",
       prompt:'Write a print() statement that outputs exactly: My name is Alex',
       hint:'print("My name is Alex")',
       check:(c,o)=>o.includes("My name is Alex"),
       checkMsg:'Output must contain: My name is Alex'},
      {type:"coding",title:"Math output",
       prompt:"Print the result of 15 multiplied by 4. Use * for multiply.",
       hint:"print(15 * 4)",
       check:(c,o)=>o.trim().includes("60"),
       checkMsg:"Output must include 60"},
    ],
    mcqs:[
      {q:"What symbol starts a comment in Python?",options:["//","/*","#","--"],answer:2},
      {q:"What does print() do?",options:["Saves a file","Displays output on screen","Creates a variable","Opens a browser"],answer:1},
      {q:'What is "Hello" in Python called?',options:["A number","A variable","A string","A function"],answer:2},
    ]
  },

  {
    id:"py2", title:"Variables & Data Types", subtitle:"Storing and labelling your data",
    intro:"Variables are named containers that hold data. Python figures out the type automatically based on what you assign — no need to declare it explicitly.",
    concepts:[
      {icon:"📦",title:"Variable", desc:"A named box storing a value. Created with = (the assignment operator)."},
      {icon:"🔢",title:"int",      desc:"Whole numbers: 1, 42, -7, 1000"},
      {icon:"💧",title:"float",    desc:"Decimal numbers: 3.14, -0.5, 99.99"},
      {icon:"💬",title:"str",      desc:'Text: "hello", \'world\''},
      {icon:"✅",title:"bool",     desc:"True or False — capital T and F required!"},
    ],
    filename:"variables.py",
    codeLines:[
      "# Creating variables",
      'name       = "Alice"',
      "age        = 25",
      "height     = 5.6",
      "is_student = True",
      "",
      "# Print them",
      'print("Name:",    name)',
      'print("Age:",     age)',
      'print("Height:",  height)',
      'print("Student?", is_student)',
      "",
      "# Check the type",
      "print(type(name))       # str",
      "print(type(age))        # int",
      "print(type(height))     # float",
      "print(type(is_student)) # bool",
    ],
    breakdown:[
      {token:'name = "Alice"',    note:"= assigns the right-hand value to the left-hand name. The variable name goes first."},
      {token:"age = 25",          note:"No quotes means Python treats 25 as an integer (whole number)."},
      {token:"height = 5.6",      note:"A decimal point makes it a float (floating-point number)."},
      {token:"is_student = True", note:"True and False (capital first letter) are Python's boolean values."},
      {token:"type(name)",        note:"The built-in type() function tells you what data type a variable holds."},
    ],
    runnable:true,
    starterCode:'name = "Your Name"\nage = 20\nis_coder = True\n\nprint("Name:", name)\nprint("Age:", age)\nprint("Coder?", is_coder)',
    challenges:[
      {type:"coding",title:"Create your profile",
       prompt:"Create variables: city (string), population (integer), sunny (boolean). Then print all three.",
       hint:'city = "Singapore"\npopulation = 5917600\nsunny = True\nprint(city, population, sunny)',
       check:(c,o)=>/city\s*=\s*["']/.test(c)&&/population\s*=\s*\d+/.test(c)&&/sunny\s*=\s*(True|False)/.test(c)&&o.length>0,
       checkMsg:"Create city (string), population (int), sunny (bool) and print them."},
    ],
    mcqs:[
      {q:"Which value is a boolean?",options:['"True"',"1","True","true"],answer:2},
      {q:"What type is the value 3.14?",options:["int","str","bool","float"],answer:3},
      {q:"Which correctly creates an integer variable?",options:['x = "5"',"x = 5","int x = 5","x == 5"],answer:1},
    ]
  },

  {
    id:"py3", title:"If / Elif / Else", subtitle:"Making decisions in code",
    intro:"Conditions let your program choose different paths — just like real-world decisions. The colon and indentation are Python's way of defining code blocks.",
    concepts:[
      {icon:"🤔",title:"if",        desc:"Run the block only if the condition is True."},
      {icon:"↔️", title:"elif",      desc:"'Else if' — another condition checked when if was False."},
      {icon:"🔄",title:"else",      desc:"Catch-all — runs when no other condition matched."},
      {icon:"⚖️",title:"Operators", desc:"== equals, != not equal, > < >= <=, and, or, not"},
    ],
    filename:"conditions.py",
    codeLines:[
      "score = 78",
      "",
      "if score >= 90:",
      '    print("Grade: A")',
      "elif score >= 80:",
      '    print("Grade: B")',
      "elif score >= 70:",
      '    print("Grade: C")',
      "else:",
      '    print("Grade: F")',
      "",
      "# and / or operators",
      "age    = 20",
      "has_id = True",
      "",
      "if age >= 18 and has_id:",
      '    print("Entry allowed")',
      "else:",
      '    print("Entry denied")',
    ],
    breakdown:[
      {token:"if score >= 90:",      note:"The colon : is required. It opens a new indented block below."},
      {token:"    print(…)",         note:"Everything indented 4 spaces under an if/elif/else belongs to that block."},
      {token:"elif",                 note:"elif = 'else if'. You can chain as many elif as needed."},
      {token:"age >= 18 and has_id", note:"and means BOTH conditions must be True. or means AT LEAST ONE must be True."},
    ],
    runnable:true,
    starterCode:"temperature = 35\n\nif temperature > 30:\n    print(\"It's hot! Stay hydrated.\")\nelif temperature > 20:\n    print(\"Nice weather.\")\nelse:\n    print(\"A bit cold today.\")",
    challenges:[
      {type:"coding",title:"Age checker",
       prompt:"Create a variable age = 17. Print 'Can vote' if age >= 18, otherwise print 'Too young'.",
       hint:"age = 17\nif age >= 18:\n    print('Can vote')\nelse:\n    print('Too young')",
       check:(c,o)=>/age\s*=/.test(c)&&o.includes("Too young"),
       checkMsg:"Set age under 18 and output must include 'Too young'"},
      {type:"coding",title:"Even or odd",
       prompt:"Create n = 7. Print 'Even' if n % 2 == 0, else print 'Odd'.",
       hint:"n = 7\nif n % 2 == 0:\n    print('Even')\nelse:\n    print('Odd')",
       check:(c,o)=>o.includes("Odd"),
       checkMsg:"Output must include 'Odd' for n=7"},
    ],
    mcqs:[
      {q:"What does == mean in Python?",options:["Assignment","Not equal","Is equal to","Greater than"],answer:2},
      {q:"How do you write 'else if' in Python?",options:["else if","elseif","elif","or if"],answer:2},
      {q:"Which operator checks that TWO conditions are both True?",options:["or","not","both","and"],answer:3},
    ]
  },

  {
    id:"py4", title:"Loops", subtitle:"Repeating actions efficiently",
    intro:"Loops run a block of code multiple times. Instead of writing the same thing 100 times, write it once and let the loop handle the repetition.",
    concepts:[
      {icon:"🔁",title:"for loop",         desc:"Iterates over a sequence — a list, range of numbers, or string."},
      {icon:"🔄",title:"while loop",       desc:"Repeats while a condition stays True."},
      {icon:"📐",title:"range()",          desc:"Generates a sequence: range(1,6) gives 1,2,3,4,5."},
      {icon:"⏩",title:"break / continue", desc:"break exits the loop early. continue skips the current iteration."},
    ],
    filename:"loops.py",
    codeLines:[
      "# for loop over a list",
      'fruits = ["apple", "banana", "mango"]',
      "for fruit in fruits:",
      '    print("I like", fruit)',
      "",
      "# for loop with range",
      "for i in range(1, 6):",
      '    print(f"{i} x 3 = {i * 3}")',
      "",
      "# while loop",
      "count = 0",
      "while count < 4:",
      '    print("Count:", count)',
      "    count += 1",
      "",
      "# break example",
      "for n in range(10):",
      "    if n == 5:",
      "        break",
      "    print(n)",
    ],
    breakdown:[
      {token:"for fruit in fruits:", note:"Each iteration, fruit takes the next value from the list automatically."},
      {token:"range(1, 6)",          note:"Generates 1,2,3,4,5 — the stop value (6) is NOT included."},
      {token:"count += 1",           note:"Shorthand for count = count + 1. Without this, the while loop runs forever!"},
      {token:"break",                note:"Immediately exits the loop. Here it stops as soon as n reaches 5."},
    ],
    runnable:true,
    starterCode:"# Print the 5 times table\nfor i in range(1, 11):\n    print(f\"5 x {i} = {5 * i}\")",
    challenges:[
      {type:"coding",title:"Sum with a loop",
       prompt:"Use a for loop and range(1,11) to calculate the sum of 1 to 10. Print the total.",
       hint:"total = 0\nfor i in range(1, 11):\n    total += i\nprint(total)",
       check:(c,o)=>o.trim().includes("55"),
       checkMsg:"Output must include 55 (sum of 1..10)"},
      {type:"coding",title:"Countdown",
       prompt:"Use a while loop to count down from 5 to 1, printing each number.",
       hint:"n = 5\nwhile n >= 1:\n    print(n)\n    n -= 1",
       check:(c,o)=>["5","4","3","2","1"].every(x=>o.includes(x)),
       checkMsg:"Output must include 5 4 3 2 1"},
    ],
    mcqs:[
      {q:"What does range(0, 5) produce?",options:["0,1,2,3,4,5","0,1,2,3,4","1,2,3,4,5","1,2,3,4"],answer:1},
      {q:"Which keyword immediately exits a loop?",options:["stop","exit","break","return"],answer:2},
      {q:"What is count += 1 equivalent to?",options:["count = 1","count + 1","count = count + 1","count = count - 1"],answer:2},
    ]
  },

  {
    id:"py5", title:"Functions", subtitle:"Reusable blocks of logic",
    intro:"Functions let you name a block of code and call it whenever needed. Write once, use many times — the backbone of clean, maintainable programs.",
    concepts:[
      {icon:"🔧",title:"def",          desc:"Keyword that defines a new function."},
      {icon:"📥",title:"Parameters",   desc:"Variables the function accepts as input."},
      {icon:"📤",title:"return",       desc:"Sends a value back to wherever the function was called."},
      {icon:"🎯",title:"Default args", desc:"Parameters with fallback values: def greet(name='World')"},
    ],
    filename:"functions.py",
    codeLines:[
      "# Basic function",
      "def greet(name):",
      '    print(f"Hello, {name}!")',
      "",
      'greet("Alice")',
      'greet("Bob")',
      "",
      "# Function with return value",
      "def add(a, b):",
      "    return a + b",
      "",
      "result = add(5, 3)",
      'print("5 + 3 =", result)',
      "",
      "# Default parameter",
      "def power(base, exp=2):",
      "    return base ** exp",
      "",
      "print(power(4))      # 16",
      "print(power(2, 10))  # 1024",
    ],
    breakdown:[
      {token:"def greet(name):",      note:"def + name + parameters in () + colon. The function body is indented below."},
      {token:"return a + b",          note:"return sends the result back. Without it, the function gives back None."},
      {token:"def power(base, exp=2)",note:"exp=2 is a default — if the caller doesn't pass exp, it uses 2."},
    ],
    runnable:true,
    starterCode:"def square(n):\n    return n * n\n\ndef cube(n):\n    return n * n * n\n\nprint(square(5))\nprint(cube(3))",
    challenges:[
      {type:"coding",title:"BMI calculator",
       prompt:"Write a function bmi(weight, height) that returns weight / (height ** 2). Call it with weight=70, height=1.75.",
       hint:"def bmi(weight, height):\n    return weight / (height ** 2)\nprint(bmi(70, 1.75))",
       check:(c,o)=>/def bmi/.test(c)&&/22/.test(o),
       checkMsg:"Function named bmi, output should contain ~22.8"},
    ],
    mcqs:[
      {q:"What keyword defines a function in Python?",options:["function","func","def","define"],answer:2},
      {q:"What does return do?",options:["Prints the value","Ends the program","Sends a value back to caller","Creates a variable"],answer:2},
      {q:"What does a function return if there is no return statement?",options:["Error","0","None","False"],answer:2},
    ]
  },

  {
    id:"py6", title:"Lists", subtitle:"Storing collections of data",
    intro:"A list holds multiple values in one variable, in order. They are one of Python's most powerful and most-used data structures.",
    concepts:[
      {icon:"📋",title:"List",    desc:"An ordered, mutable collection: [1, 2, 3]"},
      {icon:"🔢",title:"Index",   desc:"Position of an item. Starts at 0, ends at length-1."},
      {icon:"✂️", title:"Slice",   desc:"Extract a portion: list[start:end]"},
      {icon:"🔧",title:"Methods", desc:".append(), .remove(), .sort(), .pop(), len()"},
    ],
    filename:"lists.py",
    codeLines:[
      'fruits = ["apple", "banana", "mango", "grape"]',
      "",
      "# Access by index",
      "print(fruits[0])     # apple",
      "print(fruits[-1])    # grape (last)",
      "",
      "# Slicing",
      "print(fruits[1:3])   # ['banana', 'mango']",
      "",
      "# Modify",
      'fruits.append("kiwi")',
      'fruits.insert(1, "cherry")',
      'fruits.remove("banana")',
      "",
      "print(fruits)",
      "print(len(fruits))",
      "",
      "# Sorting and stats",
      "numbers = [3, 1, 4, 1, 5, 9, 2]",
      "numbers.sort()",
      "print(numbers)",
      "print(sum(numbers))",
      "print(max(numbers))",
    ],
    breakdown:[
      {token:'["apple","banana"…]', note:"Square brackets define a list. Items are separated by commas."},
      {token:"fruits[0]",           note:"Index 0 = first item. fruits[-1] = last item (negative indexes count from end)."},
      {token:"fruits[1:3]",         note:"Slice from index 1 up to (NOT including) index 3."},
      {token:"fruits.append(…)",    note:".append() adds one item to the END of the list."},
    ],
    runnable:true,
    starterCode:'colors = ["red", "green", "blue"]\nprint(colors)\ncolors.append("yellow")\nprint(colors)\nprint("Total:", len(colors))',
    challenges:[
      {type:"coding",title:"Shopping cart",
       prompt:"Create a list called cart with 3 items. Append one more item. Print the list and its length.",
       hint:'cart = ["rice","eggs","milk"]\ncart.append("bread")\nprint(cart)\nprint(len(cart))',
       check:(c,o)=>/cart\s*=\s*\[/.test(c)&&/append/.test(c)&&o.length>5,
       checkMsg:"Create 'cart', append an item, print it and its length."},
    ],
    mcqs:[
      {q:"What index is the FIRST item in a Python list?",options:["1","-1","0","first"],answer:2},
      {q:"Which method adds an item to the END of a list?",options:[".add()",".push()",".insert()",".append()"],answer:3},
      {q:"What does len([1,2,3,4]) return?",options:["3","4","5","0"],answer:1},
    ]
  },

  {
    id:"py7", title:"Dictionaries", subtitle:"Key-value data storage",
    intro:"Dictionaries store data as key-value pairs — like a real dictionary where you look up a word (key) to find its definition (value). Extremely common in real Python programs.",
    concepts:[
      {icon:"📖",title:"Dictionary", desc:"Stores data as {key: value} pairs — fast lookup by key."},
      {icon:"🔑",title:"Key",        desc:"Unique identifier used to access a value."},
      {icon:"💎",title:"Value",      desc:"The data stored at a given key — can be any type."},
      {icon:"🔧",title:"Methods",    desc:".keys(), .values(), .items(), .get()"},
    ],
    filename:"dicts.py",
    codeLines:[
      "person = {",
      '    "name": "Alice",',
      '    "age":  25,',
      '    "city": "Singapore"',
      "}",
      "",
      "# Access values",
      'print(person["name"])',
      'print(person.get("age"))   # safe access',
      "",
      "# Add / update / delete",
      'person["email"] = "alice@example.com"',
      'person["age"]   = 26',
      'del person["city"]',
      "",
      "print(person)",
      "",
      "# Loop through all key-value pairs",
      "for key, value in person.items():",
      '    print(f"  {key}: {value}")',
    ],
    breakdown:[
      {token:'{"name": "Alice"…}', note:"Curly braces {} define a dict. Each entry is key: value, items separated by commas."},
      {token:'person["name"]',     note:"Access a value by its key in square brackets."},
      {token:'person.get("age")',  note:".get() is safer — returns None instead of crashing if the key doesn't exist."},
      {token:"person.items()",     note:"Returns (key, value) pairs. Use: for k, v in d.items():"},
    ],
    runnable:true,
    starterCode:'car = {\n    "brand": "Toyota",\n    "model": "Corolla",\n    "year":  2022\n}\n\nprint(car["brand"])\nfor key, val in car.items():\n    print(key, "->", val)',
    challenges:[
      {type:"coding",title:"Phone book",
       prompt:"Create a dict contacts with 2+ names as keys and phone numbers as values. Print each with a for loop.",
       hint:'contacts = {"Alice":"9123","Bob":"8456"}\nfor name,num in contacts.items():\n    print(name,":",num)',
       check:(c,o)=>/contacts\s*=\s*{/.test(c)&&/items/.test(c)&&o.split("\n").filter(l=>l.trim()).length>=2,
       checkMsg:"contacts dict with 2+ entries, loop with .items()"},
    ],
    mcqs:[
      {q:"How do you get the value for key 'age' in dict d?",options:["d.age","d('age')","d['age']","d->age"],answer:2},
      {q:"Which method returns all key-value pairs for looping?",options:[".pairs()",".items()",".both()",".entries()"],answer:1},
      {q:"What does del d['key'] do?",options:["Deletes the whole dict","Removes that key","Returns the value","Clears all values"],answer:1},
    ]
  },
],

// ══════════════════════════════════════════════════════
//  HTML  — 6 lessons  (display-only)
// ══════════════════════════════════════════════════════
html: [
  {
    id:"h1", title:"What is HTML?", subtitle:"The skeleton of every webpage",
    intro:"HTML (HyperText Markup Language) tells the browser what content to show and how to structure it. Every website in existence uses HTML.",
    concepts:[
      {icon:"🏗️",title:"HTML",      desc:"HyperText Markup Language — the structure layer of a webpage."},
      {icon:"🏷️",title:"Tag",       desc:"Keywords in angle brackets: &lt;p&gt; is a paragraph tag."},
      {icon:"📄",title:"Element",   desc:"Opening tag + content + closing tag: &lt;p&gt;text&lt;/p&gt;"},
      {icon:"⚙️",title:"Attribute", desc:"Extra info inside a tag: &lt;a href='...'&gt;"},
    ],
    filename:"index.html",
    codeLines:[
      "<!DOCTYPE html>",
      "<html lang=\"en\">",
      "  <head>",
      "    <meta charset=\"UTF-8\">",
      "    <title>My First Page</title>",
      "  </head>",
      "  <body>",
      "    <h1>Hello, World!</h1>",
      "    <p>This is my very first web page.</p>",
      "  </body>",
      "</html>",
    ],
    breakdown:[
      {token:"&lt;!DOCTYPE html&gt;", note:"Tells the browser: this is an HTML5 document. Always the very first line."},
      {token:"&lt;head&gt;",          note:"Contains metadata — page title, stylesheets. NOT visible to users."},
      {token:"&lt;body&gt;",          note:"Everything inside body is what the user actually sees on the page."},
      {token:"&lt;h1&gt;",            note:"Heading level 1 — the main title. Use only one h1 per page."},
      {token:"&lt;p&gt;",             note:"Paragraph tag — the basic block of text content."},
    ],
    runnable:false, starterCode:"", challenges:[],
    mcqs:[
      {q:"What does HTML stand for?",options:["High Text Markup Language","HyperText Markup Language","HyperText Making Language","Home Tool Markup Language"],answer:1},
      {q:"Which tag wraps all visible page content?",options:["&lt;head&gt;","&lt;html&gt;","&lt;body&gt;","&lt;main&gt;"],answer:2},
      {q:"What does &lt;!DOCTYPE html&gt; do?",options:["Adds a comment","Declares this is HTML5","Creates a heading","Links a stylesheet"],answer:1},
    ]
  },

  {
    id:"h2", title:"Text & Headings", subtitle:"Organising content on the page",
    intro:"HTML gives you 6 heading levels, paragraphs, bold, italic, and more. Good text structure makes pages readable and accessible.",
    concepts:[
      {icon:"📰",title:"h1 to h6",   desc:"Six heading sizes — h1 is biggest, h6 is smallest."},
      {icon:"📄",title:"&lt;p&gt;",  desc:"Paragraph — the basic block of text."},
      {icon:"💪",title:"&lt;strong&gt;",desc:"Bold text, also marks importance for screen readers."},
      {icon:"✨",title:"&lt;em&gt;", desc:"Italic text — marks emphasis."},
    ],
    filename:"text.html",
    codeLines:[
      "<h1>Main Page Title</h1>",
      "<h2>Chapter 1</h2>",
      "<h3>Section 1.1</h3>",
      "",
      "<p>This is a regular paragraph. You can write as",
      "much text as you want and the browser wraps it.</p>",
      "",
      "<hr>",
      "",
      "<p>",
      "  You can have <strong>bold text</strong> and",
      "  <em>italic text</em> inside a paragraph.",
      "</p>",
      "",
      "<p>Line break:<br>Next line here.</p>",
    ],
    breakdown:[
      {token:"h1 through h6", note:"Use headings in order: h1 = main title, h2 = sections, h3 = sub-sections."},
      {token:"&lt;hr&gt;",    note:"Horizontal Rule — a self-closing tag that draws a dividing line. No closing tag needed."},
      {token:"&lt;strong&gt;",note:"Bold AND semantically important — screen readers treat this as important content."},
      {token:"&lt;em&gt;",    note:"Italic AND emphasized — the word is stressed in speech."},
      {token:"&lt;br&gt;",    note:"Line break — self-closing. Prefer CSS margin/padding for spacing in real projects."},
    ],
    runnable:false, starterCode:"", challenges:[],
    mcqs:[
      {q:"Which heading tag makes the LARGEST text?",options:["&lt;h6&gt;","&lt;h3&gt;","&lt;h1&gt;","&lt;heading&gt;"],answer:2},
      {q:"What does &lt;strong&gt; produce?",options:["Italic text","Underlined text","Bold text","Coloured text"],answer:2},
      {q:"Which tag creates a horizontal dividing line?",options:["&lt;line&gt;","&lt;divide&gt;","&lt;br&gt;","&lt;hr&gt;"],answer:3},
    ]
  },

  {
    id:"h3", title:"Links & Images", subtitle:"Connecting pages and adding visuals",
    intro:"Links are what make the web a web — they connect pages together. Both links and images use attributes to point to external resources.",
    concepts:[
      {icon:"🔗",title:"&lt;a&gt;",  desc:"Anchor tag — creates a hyperlink. href sets destination."},
      {icon:"🖼️",title:"&lt;img&gt;",desc:"Embeds an image. src = file/URL, alt = description text."},
      {icon:"⚙️",title:"href",       desc:"Hypertext Reference — the URL the link points to."},
      {icon:"📝",title:"alt",         desc:"Alternative text — shown if image fails, read by screen readers."},
    ],
    filename:"links.html",
    codeLines:[
      "<!-- Basic link -->",
      "<a href=\"https://example.com\">Visit Example.com</a>",
      "",
      "<!-- Open in new tab -->",
      "<a href=\"https://google.com\" target=\"_blank\">",
      "  Open Google in new tab",
      "</a>",
      "",
      "<!-- Link within your own site -->",
      "<a href=\"about.html\">About Us</a>",
      "",
      "<!-- Image -->",
      "<img",
      "  src=\"photo.jpg\"",
      "  alt=\"A smiling person at a desk\"",
      "  width=\"400\"",
      ">",
      "",
      "<!-- Clickable image -->",
      "<a href=\"https://example.com\">",
      "  <img src=\"logo.png\" alt=\"Site Logo\" width=\"120\">",
      "</a>",
    ],
    breakdown:[
      {token:"href=\"https://…\"",  note:"href is the destination URL. Relative paths like 'about.html' link within your own site."},
      {token:"target=\"_blank\"",   note:"Opens in a new browser tab. Without this, the current tab navigates away."},
      {token:"src=\"photo.jpg\"",   note:"Path or URL to the image. Can be a relative path or a full https:// URL."},
      {token:"alt=\"…\"",           note:"Always include alt — shown when images fail and read aloud by screen readers."},
    ],
    runnable:false, starterCode:"", challenges:[],
    mcqs:[
      {q:"Which attribute sets where a link goes?",options:["src","url","href","link"],answer:2},
      {q:"What does target='_blank' do?",options:["Makes link bold","Opens link in new tab","Styles the link","Validates the URL"],answer:1},
      {q:"Why is alt text on images important?",options:["Loads faster","Shown when image fails and read by screen readers","Sets image size","Links to another page"],answer:1},
    ]
  },

  {
    id:"h4", title:"Lists & Tables", subtitle:"Organising lists and data grids",
    intro:"Lists and tables are everywhere — navigation menus, step-by-step guides, pricing comparisons. HTML makes them straightforward with just a few tags.",
    concepts:[
      {icon:"•", title:"&lt;ul&gt;",  desc:"Unordered list — bullet points. Each item in &lt;li&gt;."},
      {icon:"1.",title:"&lt;ol&gt;",  desc:"Ordered list — numbered automatically by the browser."},
      {icon:"📊",title:"&lt;table&gt;",desc:"Grid of rows and columns for tabular data."},
      {icon:"📋",title:"tr / th / td", desc:"tr = row, th = header cell, td = data cell."},
    ],
    filename:"lists_tables.html",
    codeLines:[
      "<!-- Unordered list -->",
      "<ul>",
      "  <li>Apples</li>",
      "  <li>Bananas</li>",
      "  <li>Mangoes</li>",
      "</ul>",
      "",
      "<!-- Ordered list -->",
      "<ol>",
      "  <li>Boil water</li>",
      "  <li>Add pasta</li>",
      "  <li>Cook 10 minutes</li>",
      "</ol>",
      "",
      "<!-- Table -->",
      "<table border=\"1\">",
      "  <thead>",
      "    <tr><th>Name</th><th>Age</th><th>City</th></tr>",
      "  </thead>",
      "  <tbody>",
      "    <tr><td>Alice</td><td>25</td><td>Singapore</td></tr>",
      "    <tr><td>Bob</td><td>30</td><td>London</td></tr>",
      "  </tbody>",
      "</table>",
    ],
    breakdown:[
      {token:"&lt;ul&gt; / &lt;ol&gt;", note:"ul = unordered (bullets), ol = ordered (numbers). Both need &lt;li&gt; for each item."},
      {token:"&lt;li&gt;",              note:"List Item — required for every bullet or numbered entry."},
      {token:"&lt;table&gt;",           note:"Wraps the entire table. border='1' adds a simple visible border."},
      {token:"&lt;th&gt;",              note:"Table Header cell — bold and centred by default. Use for column labels."},
      {token:"&lt;td&gt;",              note:"Table Data cell — one &lt;td&gt; per column per row."},
    ],
    runnable:false, starterCode:"", challenges:[],
    mcqs:[
      {q:"Which tag creates a NUMBERED list?",options:["&lt;ul&gt;","&lt;nl&gt;","&lt;list&gt;","&lt;ol&gt;"],answer:3},
      {q:"What tag makes a header cell in a table?",options:["&lt;td&gt;","&lt;header&gt;","&lt;th&gt;","&lt;tc&gt;"],answer:2},
      {q:"What tag must every list item use?",options:["&lt;item&gt;","&lt;li&gt;","&lt;bullet&gt;","&lt;entry&gt;"],answer:1},
    ]
  },

  {
    id:"h5", title:"Forms & Inputs", subtitle:"Collecting data from users",
    intro:"Forms are how websites collect information — logins, registrations, search bars, contact forms. Every interactive website relies on form elements.",
    concepts:[
      {icon:"📋",title:"&lt;form&gt;",    desc:"Container for all input elements."},
      {icon:"✏️", title:"&lt;input&gt;",   desc:"Single-line data entry. type attribute changes behaviour."},
      {icon:"📝",title:"&lt;textarea&gt;",desc:"Multi-line text input."},
      {icon:"🏷️",title:"&lt;label&gt;",   desc:"Describes an input. Clicking label focuses its input."},
    ],
    filename:"form.html",
    codeLines:[
      "<form action=\"/submit\" method=\"POST\">",
      "",
      "  <label for=\"name\">Full Name:</label>",
      "  <input type=\"text\" id=\"name\" name=\"name\"",
      "         placeholder=\"Enter your name\" required>",
      "",
      "  <label for=\"email\">Email:</label>",
      "  <input type=\"email\" id=\"email\" name=\"email\"",
      "         placeholder=\"you@example.com\">",
      "",
      "  <label for=\"age\">Age:</label>",
      "  <input type=\"number\" id=\"age\" min=\"1\" max=\"120\">",
      "",
      "  <label for=\"msg\">Message:</label>",
      "  <textarea id=\"msg\" rows=\"4\"",
      "            placeholder=\"Your message...\"></textarea>",
      "",
      "  <label>",
      "    <input type=\"checkbox\" name=\"agree\">",
      "    I agree to the terms",
      "  </label>",
      "",
      "  <button type=\"submit\">Send</button>",
      "",
      "</form>",
    ],
    breakdown:[
      {token:"method=\"POST\"",          note:"POST sends data in the request body (for passwords etc). GET appends it to the URL."},
      {token:"for=\"name\" / id=\"name\"",note:"Linking label for= to input id= makes the label clickable to focus the field."},
      {token:"type=\"email\"",           note:"Browser validates the input looks like an email address before allowing submit."},
      {token:"required",                 note:"Boolean attribute — browser blocks submit if this field is empty."},
      {token:"&lt;textarea&gt;",         note:"Unlike input, textarea allows multi-line text entry."},
    ],
    runnable:false, starterCode:"", challenges:[],
    mcqs:[
      {q:"Which input type validates email format?",options:["type=\"text\"","type=\"mail\"","type=\"email\"","type=\"address\""],answer:2},
      {q:"What attribute makes a field mandatory?",options:["mandatory","required","must","validate"],answer:1},
      {q:"Which element allows multi-line text input?",options:["&lt;input type='multi'&gt;","&lt;multiline&gt;","&lt;textarea&gt;","&lt;input rows='4'&gt;"],answer:2},
    ]
  },

  {
    id:"h6", title:"Semantic HTML & CSS Intro", subtitle:"Meaning + style",
    intro:"Semantic tags tell browsers and developers what each part of a page IS. CSS adds visual style — colours, fonts, spacing. Together they make beautiful, accessible pages.",
    concepts:[
      {icon:"🧭",title:"&lt;header&gt;/&lt;nav&gt;",  desc:"Site header and navigation links."},
      {icon:"📰",title:"&lt;main&gt;/&lt;article&gt;",desc:"Primary content and self-contained pieces."},
      {icon:"🦶",title:"&lt;footer&gt;",              desc:"Bottom of page — copyright, links."},
      {icon:"🎨",title:"CSS &lt;style&gt;",            desc:"Rules like: body { color: red; font-size: 16px; }"},
    ],
    filename:"semantic.html",
    codeLines:[
      "<!DOCTYPE html>",
      "<html lang=\"en\">",
      "<head>",
      "  <title>My Blog</title>",
      "  <style>",
      "    body   { font-family: sans-serif; margin: 20px; }",
      "    header { background: #222; color: white; padding: 10px; }",
      "    nav a  { color: #0af; margin-right: 10px; }",
      "    footer { border-top: 1px solid #ccc; padding-top: 10px; }",
      "  </style>",
      "</head>",
      "<body>",
      "  <header>",
      "    <h1>My Tech Blog</h1>",
      "    <nav>",
      "      <a href=\"/\">Home</a>",
      "      <a href=\"/about\">About</a>",
      "    </nav>",
      "  </header>",
      "  <main>",
      "    <article>",
      "      <h2>How I Learned Python</h2>",
      "      <p>It all started with CodePath...</p>",
      "    </article>",
      "  </main>",
      "  <footer><p>2025 My Blog</p></footer>",
      "</body>",
      "</html>",
    ],
    breakdown:[
      {token:"&lt;header&gt;",  note:"Site or section header. Screen readers announce this as a page landmark."},
      {token:"&lt;nav&gt;",     note:"Marks navigation links. Users can jump directly to nav with keyboard shortcuts."},
      {token:"&lt;main&gt;",    note:"Primary content — unique per page. Only ONE main element per document."},
      {token:"&lt;article&gt;", note:"Standalone content that makes sense on its own (blog post, news item)."},
      {token:"&lt;style&gt;",   note:"CSS rules go inside style in the head. Format: selector { property: value; }"},
    ],
    runnable:false, starterCode:"", challenges:[],
    mcqs:[
      {q:"Which tag wraps a self-contained blog post?",options:["&lt;div&gt;","&lt;section&gt;","&lt;article&gt;","&lt;post&gt;"],answer:2},
      {q:"How many &lt;main&gt; elements should a page have?",options:["As many as needed","Two","One","None"],answer:2},
      {q:"Where do CSS &lt;style&gt; rules go?",options:["Inside &lt;body&gt;","Inside &lt;head&gt;","Inside &lt;footer&gt;","Inside &lt;main&gt;"],answer:1},
    ]
  },
],

// ══════════════════════════════════════════════════════
//  JAVASCRIPT  — 7 lessons
// ══════════════════════════════════════════════════════
js: [
  {
    id:"js1", title:"Hello, JavaScript!", subtitle:"The language of the web",
    intro:"JavaScript runs directly in the browser and makes websites interactive. It is the only programming language browsers natively understand — making it essential for web development.",
    concepts:[
      {icon:"⚡",title:"JavaScript",  desc:"The programming language that runs in web browsers (and on servers via Node.js)."},
      {icon:"🖥️",title:"console.log", desc:"Prints output — like Python's print(). Check it in DevTools (F12 → Console)."},
      {icon:"📝",title:"let / const", desc:"let: changeable variable. const: constant that can't be reassigned."},
      {icon:"//",title:"Comment",    desc:"// for single-line, /* */ for multi-line comments."},
    ],
    filename:"hello.js",
    codeLines:[
      "// Single-line comment",
      "console.log('Hello, World!');",
      "",
      "/* Multi-line comment */",
      "",
      "// Variables",
      "let name = 'Alice';      // can change later",
      "const PI = 3.14159;      // cannot change",
      "",
      "console.log('Name:', name);",
      "console.log('PI:', PI);",
      "",
      "// Template literals (modern, preferred)",
      "console.log(`Hello, ${name}! PI is ${PI}`);",
      "",
      "// Math",
      "console.log(10 + 5);   // 15",
      "console.log(10 ** 2);  // 100",
    ],
    breakdown:[
      {token:"console.log()", note:"Outputs to the browser console. In this editor it shows in the output box below."},
      {token:"let name = 'Alice'", note:"let creates a variable you can reassign. Always prefer let over the old var keyword."},
      {token:"const PI = 3.14",   note:"const = constant. JS throws an error if you try to reassign it."},
      {token:"`Hello, ${name}`",  note:"Template literals use backticks and ${} to embed variables cleanly — no + needed."},
    ],
    runnable:true,
    starterCode:"let name = 'World';\nconst year = 2025;\n\nconsole.log('Hello, ' + name + '!');\nconsole.log(`The year is ${year}`);",
    challenges:[
      {type:"coding",title:"Introduce yourself",
       prompt:"Create const variables for your name and age. Log: 'My name is [name] and I am [age] years old.' using a template literal.",
       hint:"const name = 'Sam';\nconst age = 22;\nconsole.log(`My name is ${name} and I am ${age} years old.`);",
       check:(c,o)=>/const/.test(c)&&/My name is/.test(o),
       checkMsg:"Use const and a template literal. Output must start with 'My name is'"},
    ],
    mcqs:[
      {q:"Which keyword creates a constant (non-reassignable) variable?",options:["let","var","const","fixed"],answer:2},
      {q:"What syntax embeds a variable in a template literal?",options:["#{name}","${name}","[name]","@{name}"],answer:1},
      {q:"How do you write a single-line comment in JS?",options:["#","//","--","/*"],answer:1},
    ]
  },

  {
    id:"js2", title:"Functions", subtitle:"Reusable blocks of logic",
    intro:"JavaScript has traditional function declarations and modern arrow functions. Arrow functions are now the standard in most professional codebases.",
    concepts:[
      {icon:"🔧",title:"function",      desc:"Traditional declaration — hoisted (can call before it appears in code)."},
      {icon:"➡️", title:"Arrow fn",     desc:"const fn = () => {} — modern, concise syntax."},
      {icon:"📤",title:"return",        desc:"Sends a value back to the caller."},
      {icon:"🎯",title:"Default param", desc:"function greet(name = 'World') — fallback if no argument given."},
    ],
    filename:"functions.js",
    codeLines:[
      "// Traditional function",
      "function greet(name) {",
      "  console.log('Hello, ' + name + '!');",
      "}",
      "greet('Alice');",
      "",
      "// Function with return",
      "function add(a, b) {",
      "  return a + b;",
      "}",
      "console.log('Sum:', add(5, 3));",
      "",
      "// Default parameter",
      "function power(base, exp = 2) {",
      "  return base ** exp;",
      "}",
      "console.log(power(4));       // 16",
      "console.log(power(2, 10));   // 1024",
      "",
      "// Arrow function (modern)",
      "const multiply = (a, b) => a * b;",
      "console.log(multiply(4, 5)); // 20",
    ],
    breakdown:[
      {token:"function greet(name)",     note:"Traditional declaration — can be called anywhere in the file (hoisted)."},
      {token:"const multiply = (a,b) => a*b", note:"Arrow one-liner — no braces needed. The expression is returned automatically."},
      {token:"exp = 2",                  note:"Default parameter — if caller doesn't pass exp, it defaults to 2."},
      {token:"return a + b",             note:"Sends the result back. Without return, a function gives back undefined."},
    ],
    runnable:true,
    starterCode:"function square(n) {\n  return n * n;\n}\n\nconst cube = (n) => n * n * n;\n\nconsole.log(square(5));\nconsole.log(cube(3));",
    challenges:[
      {type:"coding",title:"Temperature converter",
       prompt:"Write an arrow function celsiusToF(c) that returns c * 9/5 + 32. Log results for 0 and 100.",
       hint:"const celsiusToF = (c) => c * 9/5 + 32;\nconsole.log(celsiusToF(0));\nconsole.log(celsiusToF(100));",
       check:(c,o)=>/=>/.test(c)&&o.includes("32")&&o.includes("212"),
       checkMsg:"Use arrow function. Output must include 32 and 212."},
    ],
    mcqs:[
      {q:"What does an arrow one-liner implicitly do?",options:["Logs the value","Returns the expression","Creates a loop","Declares a variable"],answer:1},
      {q:"What does a function return with no return statement?",options:["0","false","null","undefined"],answer:3},
      {q:"What is a default parameter?",options:["A required argument","A fallback value if none provided","The first argument","A global variable"],answer:1},
    ]
  },

  {
    id:"js3", title:"Arrays & Loops", subtitle:"Working with collections of data",
    intro:"Arrays hold ordered lists of values. Modern JavaScript has powerful array methods — map, filter, reduce — that make data processing clean and expressive.",
    concepts:[
      {icon:"📋",title:"Array",   desc:"Ordered list: [1,2,3]. Index starts at 0."},
      {icon:"🔁",title:"forEach", desc:"Loop through each item with a callback."},
      {icon:"🗺️", title:"map",    desc:"Transform each item and return a NEW array."},
      {icon:"🔍",title:"filter",  desc:"Return only items that pass a test."},
    ],
    filename:"arrays.js",
    codeLines:[
      "const fruits = ['apple', 'banana', 'mango'];",
      "",
      "// Access",
      "console.log(fruits[0]);       // apple",
      "console.log(fruits.length);   // 3",
      "",
      "// Add / remove",
      "fruits.push('grape');",
      "const last = fruits.pop();",
      "console.log(fruits);",
      "",
      "// forEach",
      "fruits.forEach((fruit, i) => {",
      "  console.log(`${i}: ${fruit}`);",
      "});",
      "",
      "// map — transform to new array",
      "const nums = [1, 2, 3, 4, 5];",
      "const squared = nums.map(n => n * n);",
      "console.log(squared);",
      "",
      "// filter — keep matching items",
      "const evens = nums.filter(n => n % 2 === 0);",
      "console.log(evens);",
      "",
      "// reduce — combine to one value",
      "const total = nums.reduce((sum, n) => sum + n, 0);",
      "console.log('Sum:', total);",
    ],
    breakdown:[
      {token:"fruits[0]",                note:"Index 0 = first item. Use fruits[fruits.length-1] for last (not -1 like Python)."},
      {token:"fruits.push(…)",           note:"push() adds to end. pop() removes last. unshift() adds to start. shift() removes first."},
      {token:"nums.map(n => n*n)",       note:"map returns a NEW array with each item transformed. Original is unchanged."},
      {token:"nums.filter(n => n%2===0)",note:"filter returns a NEW array of only items where the callback returns true."},
      {token:"reduce((sum,n)=>sum+n, 0)",note:"reduce collapses an array to a single value. Second arg (0) is the starting value."},
    ],
    runnable:true,
    starterCode:"const numbers = [1, 2, 3, 4, 5];\n\nconst doubled = numbers.map(n => n * 2);\nconsole.log(doubled);\n\nconst total = numbers.reduce((sum, n) => sum + n, 0);\nconsole.log('Total:', total);",
    challenges:[
      {type:"coding",title:"Filter and map",
       prompt:"Given nums = [1,2,3,4,5,6], filter to get only evens, then map to square them. Log the result.",
       hint:"const nums = [1,2,3,4,5,6];\nconst result = nums.filter(n => n%2===0).map(n => n*n);\nconsole.log(result);",
       check:(c,o)=>o.includes("4")&&o.includes("16")&&o.includes("36"),
       checkMsg:"Output must include 4, 16, 36 (squares of 2, 4, 6)"},
    ],
    mcqs:[
      {q:"What does .map() return?",options:["Same array modified","A new transformed array","A single value","undefined"],answer:1},
      {q:"What does .filter() return?",options:["First matching item","A count","New array of matching items","true or false"],answer:2},
      {q:"What index is the FIRST item in a JS array?",options:["1","0","-1","first"],answer:1},
    ]
  },

  {
    id:"js4", title:"Objects", subtitle:"Structured data with named properties",
    intro:"Objects store data as key-value pairs — like Python dictionaries. Almost everything in JavaScript is an object, making this one of the most important concepts to master.",
    concepts:[
      {icon:"📦",title:"Object",   desc:"Collection of properties: { key: value }"},
      {icon:"🔑",title:"Property", desc:"A named value inside an object."},
      {icon:"🔧",title:"Method",   desc:"A function stored as a property of an object."},
      {icon:"🪄",title:"this",     desc:"Refers to the current object inside a method."},
    ],
    filename:"objects.js",
    codeLines:[
      "const person = {",
      "  name: 'Alice',",
      "  age:  25,",
      "  city: 'Singapore',",
      "  greet() {",
      "    console.log(`Hi, I'm ${this.name}!`);",
      "  }",
      "};",
      "",
      "// Access properties",
      "console.log(person.name);",
      "console.log(person['age']);  // bracket notation",
      "",
      "// Add / update / delete",
      "person.email = 'alice@example.com';",
      "person.age = 26;",
      "delete person.city;",
      "",
      "// Call a method",
      "person.greet();",
      "",
      "// Loop through properties",
      "for (const key in person) {",
      "  console.log(`${key}: ${person[key]}`);",
      "}",
    ],
    breakdown:[
      {token:"{ name: 'Alice' … }",  note:"Object literal — curly braces, key: value pairs, separated by commas."},
      {token:"person.name",          note:"Dot notation — the most common way to access a property."},
      {token:"person['age']",        note:"Bracket notation — useful when the key is in a variable or has special characters."},
      {token:"greet() { … }",        note:"A method — a function defined as a property of the object."},
      {token:"this.name",            note:"Inside a method, this refers to the object the method belongs to."},
    ],
    runnable:true,
    starterCode:"const car = {\n  brand: 'Toyota',\n  model: 'Corolla',\n  year:  2022,\n  describe() {\n    console.log(`${this.brand} ${this.model} (${this.year})`);\n  }\n};\n\nconsole.log(car.brand);\ncar.describe();",
    challenges:[
      {type:"coding",title:"Book object",
       prompt:"Create an object book with title, author, year. Add a method summary() that logs '[title] by [author] (year)'. Call it.",
       hint:"const book = { title:'Dune', author:'Herbert', year:1965, summary() { console.log(`${this.title} by ${this.author} (${this.year})`); } };\nbook.summary();",
       check:(c,o)=>/summary/.test(c)&&/by/.test(o),
       checkMsg:"Create book object with summary() method that includes 'by'"},
    ],
    mcqs:[
      {q:"What does 'this' refer to inside a method?",options:["The window","The function itself","The object the method belongs to","The parent object"],answer:2},
      {q:"How do you remove a property from an object?",options:["remove obj.key","obj.key = null","delete obj.key","obj.pop(key)"],answer:2},
      {q:"Which notation allows using a variable as a key?",options:["obj.key","obj->key","obj[key]","obj{key}"],answer:2},
    ]
  },

  {
    id:"js5", title:"Conditions & Loops", subtitle:"Control flow in JavaScript",
    intro:"JavaScript conditions and loops work like Python but use curly braces instead of indentation. These are the building blocks of all program logic.",
    concepts:[
      {icon:"🤔",title:"if/else",   desc:"Runs code conditionally — same logic as Python but with {} braces."},
      {icon:"🔁",title:"for loop",  desc:"Classic init; condition; step loop."},
      {icon:"🔄",title:"while loop",desc:"Repeats while condition is true."},
      {icon:"🎛️",title:"switch",    desc:"Clean alternative to many else-if chains."},
    ],
    filename:"control.js",
    codeLines:[
      "const score = 78;",
      "",
      "if (score >= 90) {",
      "  console.log('A');",
      "} else if (score >= 70) {",
      "  console.log('B');",
      "} else {",
      "  console.log('F');",
      "}",
      "",
      "// for loop",
      "for (let i = 1; i <= 5; i++) {",
      "  console.log(`${i} x 2 = ${i * 2}`);",
      "}",
      "",
      "// while loop",
      "let n = 3;",
      "while (n > 0) {",
      "  console.log(n);",
      "  n--;",
      "}",
      "",
      "// switch",
      "const day = 'Mon';",
      "switch (day) {",
      "  case 'Mon': console.log('Start of week'); break;",
      "  case 'Fri': console.log('TGIF!'); break;",
      "  default:    console.log('Midweek');",
      "}",
    ],
    breakdown:[
      {token:"if (score >= 90) {",       note:"Condition in parentheses. Body in curly braces {} — NOT indentation like Python."},
      {token:"for (let i=1; i<=5; i++)", note:"Three parts: initialise (let i=1), condition (i<=5), step (i++)."},
      {token:"i++",                       note:"Shorthand for i = i + 1. n-- means n = n - 1."},
      {token:"switch (day) {",            note:"switch evaluates once and jumps to matching case. break prevents fall-through."},
    ],
    runnable:true,
    starterCode:"let total = 0;\nfor (let i = 1; i <= 10; i++) {\n  total += i;\n}\nconsole.log('Sum:', total);",
    challenges:[
      {type:"coding",title:"FizzBuzz",
       prompt:"Loop 1 to 15. Log 'Fizz' if divisible by 3, 'Buzz' if by 5, 'FizzBuzz' if both, else the number.",
       hint:"for(let i=1;i<=15;i++){\n  if(i%15===0)console.log('FizzBuzz');\n  else if(i%3===0)console.log('Fizz');\n  else if(i%5===0)console.log('Buzz');\n  else console.log(i);\n}",
       check:(c,o)=>o.includes("FizzBuzz")&&o.includes("Fizz")&&o.includes("Buzz"),
       checkMsg:"Output must include FizzBuzz, Fizz, and Buzz"},
    ],
    mcqs:[
      {q:"What wraps code blocks in JS instead of indentation?",options:["Parentheses ()","Square brackets []","Curly braces {}","Angle brackets <>"],answer:2},
      {q:"What does i++ do?",options:["Multiplies i by itself","Subtracts 1","Adds 1","Resets i to 0"],answer:2},
      {q:"What does break do in a switch?",options:["Ends the program","Prevents fall-through","Skips current case","Throws an error"],answer:1},
    ]
  },

  {
    id:"js6", title:"DOM Manipulation", subtitle:"Making web pages interactive",
    intro:"The DOM (Document Object Model) is JavaScript's interface to HTML. You can select elements and change their content, style, or create new ones — all in real time.",
    concepts:[
      {icon:"🌳",title:"DOM",             desc:"The tree of HTML elements JavaScript can read and modify."},
      {icon:"🎯",title:"querySelector",   desc:"Selects elements using CSS selectors (modern, preferred)."},
      {icon:"✏️", title:"textContent",    desc:"Read or change the plain text inside an element."},
      {icon:"🎨",title:"classList",       desc:"Add, remove, or toggle CSS classes dynamically."},
    ],
    filename:"dom.js",
    codeLines:[
      "// Select elements",
      "const title = document.querySelector('h1');",
      "const btn   = document.querySelector('#myBtn');",
      "const items = document.querySelectorAll('.item');",
      "",
      "// Change content",
      "title.textContent = 'New Title!';",
      "title.innerHTML = 'Title with <em>italic</em>';",
      "",
      "// Change style",
      "title.style.color    = 'blue';",
      "title.style.fontSize = '2rem';",
      "",
      "// Add / remove / toggle CSS classes",
      "title.classList.add('highlight');",
      "title.classList.remove('old-class');",
      "title.classList.toggle('active');",
      "",
      "// Handle a click event",
      "btn.addEventListener('click', () => {",
      "  title.textContent = 'Button clicked!';",
      "});",
      "",
      "// Create new element",
      "const p = document.createElement('p');",
      "p.textContent = 'I was created by JS!';",
      "document.body.appendChild(p);",
    ],
    breakdown:[
      {token:"querySelector('#myBtn')",  note:"Takes any CSS selector. # for id, . for class, tag name for element type."},
      {token:"querySelectorAll('.item')",note:"Returns ALL matching elements as a NodeList — loop through it like an array."},
      {token:"textContent",              note:"Gets/sets plain text. Safer than innerHTML (prevents script injection)."},
      {token:"addEventListener('click')",note:"Attaches an event handler. Much better than inline onclick= attributes."},
    ],
    runnable:true,
    starterCode:"// Simulate DOM interaction\nlet count = 0;\nfunction handleClick() {\n  count++;\n  console.log('Button clicked! Count:', count);\n}\nhandleClick();\nhandleClick();\nhandleClick();",
    challenges:[
      {type:"coding",title:"Event counter",
       prompt:"Start count=0. Write handleClick() that increments it and logs 'Clicked N times'. Call it 3 times.",
       hint:"let count = 0;\nfunction handleClick() { count++; console.log('Clicked ' + count + ' times'); }\nhandleClick(); handleClick(); handleClick();",
       check:(c,o)=>/count/.test(c)&&o.includes("3"),
       checkMsg:"Output must include '3' after 3 clicks"},
    ],
    mcqs:[
      {q:"What does querySelector('#btn') select?",options:["All elements with class btn","Element with id btn","All buttons","The first button"],answer:1},
      {q:"Which property safely sets plain text content?",options:["innerHTML","outerHTML","textContent","nodeValue"],answer:2},
      {q:"What method attaches an event handler?",options:["attachEvent()","onEvent()","addEventListener()","listenFor()"],answer:2},
    ]
  },

  {
    id:"js7", title:"Fetch & Async/Await", subtitle:"Getting data from the internet",
    intro:"Modern web apps constantly load data from APIs — weather, user data, social feeds. JavaScript's fetch() and async/await make this clean and readable.",
    concepts:[
      {icon:"🌐",title:"fetch()",     desc:"Built-in function to make HTTP requests to APIs."},
      {icon:"⏳",title:"async/await", desc:"Makes async code look like sync code — much easier to read."},
      {icon:"📦",title:"JSON",        desc:"JavaScript Object Notation — the standard web API data format."},
      {icon:"🛡️",title:"try/catch",   desc:"Handle errors gracefully when requests fail."},
    ],
    filename:"fetch.js",
    codeLines:[
      "// With async/await (clean, modern approach)",
      "async function getUser(id) {",
      "  try {",
      "    const response = await fetch(",
      "      `https://jsonplaceholder.typicode.com/users/${id}`",
      "    );",
      "",
      "    if (!response.ok) {",
      "      throw new Error('Network response was not ok');",
      "    }",
      "",
      "    const user = await response.json();",
      "    console.log(user.name, '-', user.email);",
      "    return user;",
      "",
      "  } catch (error) {",
      "    console.error('Failed:', error.message);",
      "  }",
      "}",
      "",
      "getUser(1);",
      "",
      "// Promise chain (older style, same result)",
      "fetch('https://jsonplaceholder.typicode.com/users/2')",
      "  .then(res => res.json())",
      "  .then(user => console.log(user.name))",
      "  .catch(err => console.error(err));",
    ],
    breakdown:[
      {token:"async function …",     note:"Adding async lets you use await inside. The function automatically returns a Promise."},
      {token:"await fetch(url)",     note:"Pauses execution until the network response arrives — without blocking the browser."},
      {token:"await response.json()",note:"Parses the response as JSON. Also returns a Promise, so await is needed again."},
      {token:"try { … } catch { }",  note:"Wraps risky code. Any error (network failure, bad JSON) is caught gracefully."},
    ],
    runnable:true,
    starterCode:"async function fetchData() {\n  const data = await Promise.resolve({ name: 'Alice', age: 25 });\n  console.log('Got:', data.name, data.age);\n}\n\nfetchData();",
    challenges:[
      {type:"coding",title:"Async simulation",
       prompt:"Write an async function wait() that awaits Promise.resolve('done') and logs the result. Call it.",
       hint:"async function wait() {\n  const result = await Promise.resolve('done');\n  console.log(result);\n}\nwait();",
       check:(c,o)=>o.includes("done"),
       checkMsg:"Output must include 'done'"},
    ],
    mcqs:[
      {q:"What does await do?",options:["Creates a new thread","Pauses until the Promise resolves","Runs code in parallel","Cancels a fetch"],answer:1},
      {q:"What format do most web APIs return data in?",options:["XML","CSV","JSON","HTML"],answer:2},
      {q:"What does async before a function enable?",options:["Parallel execution","Using await inside it","Automatic error handling","Faster performance"],answer:1},
    ]
  },
],

// ══════════════════════════════════════════════════════
//  C++  — 6 lessons  (display-only, not executed)
// ══════════════════════════════════════════════════════
cpp: [
  {
    id:"cpp1", title:"Hello, World!", subtitle:"Your first compiled program",
    intro:"C++ is a powerful compiled language. Unlike Python/JS which run line by line, C++ is transformed into machine code before running — making it extremely fast. Used in games, operating systems, and system software.",
    concepts:[
      {icon:"⚙️",title:"C++",      desc:"Compiled, statically-typed, high-performance language."},
      {icon:"📦",title:"#include", desc:"Import a library of pre-built code."},
      {icon:"🚪",title:"main()",   desc:"Entry point — every C++ program starts here."},
      {icon:"📣",title:"cout",     desc:"Console output — like print() in Python."},
    ],
    filename:"hello.cpp",
    codeLines:[
      "// These lines are always needed",
      "#include <iostream>",
      "using namespace std;",
      "",
      "// The main function — where the program starts",
      "int main() {",
      '    cout << "Hello, World!" << endl;',
      '    cout << "Welcome to C++!" << endl;',
      "",
      "    // Math works too",
      "    cout << 10 + 5  << endl;  // 15",
      "    cout << 10 * 3  << endl;  // 30",
      "",
      "    return 0;  // 0 = success",
      "}",
    ],
    breakdown:[
      {token:"#include &lt;iostream&gt;",  note:"Imports the Input/Output Stream library — needed for cout and cin."},
      {token:"using namespace std;",        note:"Lets you write cout instead of std::cout. Saves typing in beginner code."},
      {token:"int main() { … }",           note:"main() is mandatory — the OS calls this to start your program. int = returns an integer."},
      {token:"cout &lt;&lt; … &lt;&lt; endl", note:"cout = console output. << feeds data into the stream. endl = newline + flush."},
      {token:"return 0;",                  note:"Tells the OS the program finished successfully. Non-zero values indicate errors."},
    ],
    runnable:false, starterCode:"", challenges:[],
    mcqs:[
      {q:"What does #include &lt;iostream&gt; do?",options:["Creates a function","Imports the I/O library","Starts the program","Defines a variable"],answer:1},
      {q:"What is the entry point of every C++ program?",options:["start()","begin()","main()","init()"],answer:2},
      {q:"What does return 0 mean at the end of main()?",options:["Restart the program","Program succeeded","Return value 0 to a variable","Loop 0 times"],answer:1},
    ]
  },

  {
    id:"cpp2", title:"Variables & Data Types", subtitle:"Strongly typed storage",
    intro:"C++ is statically typed — you MUST declare the type of every variable. This strictness makes programs faster and catches type bugs at compile time before the program even runs.",
    concepts:[
      {icon:"🔢",title:"int",    desc:"Whole numbers: 1, -5, 100"},
      {icon:"💧",title:"double", desc:"Decimal numbers: 3.14, -0.5 (more precise than float)"},
      {icon:"💬",title:"string", desc:'Text: "hello" — needs #include &lt;string&gt;'},
      {icon:"✅",title:"bool",   desc:"true or false (lowercase in C++)"},
    ],
    filename:"variables.cpp",
    codeLines:[
      "#include <iostream>",
      "#include <string>",
      "using namespace std;",
      "",
      "int main() {",
      "    // Type goes BEFORE the variable name",
      '    string name      = "Alice";',
      "    int    age       = 25;",
      "    double height    = 5.9;",
      "    bool   isStudent = true;",
      "",
      '    cout << "Name:    " << name      << endl;',
      '    cout << "Age:     " << age       << endl;',
      '    cout << "Height:  " << height    << endl;',
      '    cout << "Student: " << isStudent << endl;',
      "",
      "    // const — value can never change",
      "    const double PI = 3.14159;",
      '    cout << "PI: " << PI << endl;',
      "",
      "    return 0;",
      "}",
    ],
    breakdown:[
      {token:'string name = "Alice"',  note:"You MUST put the type before the variable name. C++ is explicit about types."},
      {token:"double height = 5.9",    note:"Use double for decimals — more precise than float (64-bit vs 32-bit)."},
      {token:"bool isStudent = true",  note:"In C++, booleans are lowercase: true and false (unlike Python's True/False)."},
      {token:"const double PI",        note:"const makes a variable immutable — similar to const in JavaScript."},
    ],
    runnable:false, starterCode:"", challenges:[],
    mcqs:[
      {q:"Which C++ type stores decimal numbers best?",options:["int","decimal","double","float64"],answer:2},
      {q:"What are C++ boolean values?",options:["True/False","TRUE/FALSE","true/false","yes/no"],answer:2},
      {q:"Which header is needed to use the string type?",options:["&lt;text&gt;","&lt;string&gt;","&lt;iostream&gt;","&lt;str&gt;"],answer:1},
    ]
  },

  {
    id:"cpp3", title:"Conditions & User Input", subtitle:"Decisions + reading from keyboard",
    intro:"C++ conditions use curly braces like JavaScript. You can read input from the user with cin — the counterpart to cout.",
    concepts:[
      {icon:"🤔",title:"if/else", desc:"Same logic as Python but with () for condition and {} for block."},
      {icon:"⌨️",title:"cin",    desc:"Console input — reads data typed by the user."},
      {icon:"🎛️",title:"switch", desc:"Clean multi-way branching on a single value."},
    ],
    filename:"conditions.cpp",
    codeLines:[
      "#include <iostream>",
      "#include <string>",
      "using namespace std;",
      "",
      "int main() {",
      "    int score = 78;",
      "",
      "    if (score >= 90) {",
      '        cout << "Grade: A" << endl;',
      "    } else if (score >= 80) {",
      '        cout << "Grade: B" << endl;',
      "    } else if (score >= 70) {",
      '        cout << "Grade: C" << endl;',
      "    } else {",
      '        cout << "Grade: F" << endl;',
      "    }",
      "",
      "    // Reading user input with cin",
      "    string name;",
      '    cout << "Enter your name: ";',
      "    cin >> name;",
      '    cout << "Hello, " << name << "!" << endl;',
      "",
      "    return 0;",
      "}",
    ],
    breakdown:[
      {token:"if (score >= 90) {",  note:"Condition in parentheses (), body in curly braces {}. Same structure as JavaScript."},
      {token:"else if",             note:"Two words (same as JavaScript). Python uses 'elif' but C++ and JS use 'else if'."},
      {token:"cin >> name",         note:"cin reads from keyboard. >> is the extraction operator (opposite direction of <<)."},
    ],
    runnable:false, starterCode:"", challenges:[],
    mcqs:[
      {q:"How does C++ write 'else if'?",options:["elif","elseif","else if","otherwise"],answer:2},
      {q:"Which reads keyboard input in C++?",options:["cout <<","cin >>","scanf","read"],answer:1},
      {q:"What wraps code blocks in C++ conditions?",options:["Parentheses ()","Square brackets []","Curly braces {}","Indentation"],answer:2},
    ]
  },

  {
    id:"cpp4", title:"Loops", subtitle:"Repeating actions in C++",
    intro:"C++ loops look identical to JavaScript loops. The for loop syntax with init; condition; step is shared between both languages.",
    concepts:[
      {icon:"🔁",title:"for loop",    desc:"Classic init; condition; step — most common loop in C++."},
      {icon:"🔄",title:"while loop",  desc:"Repeats while condition is true."},
      {icon:"🔂",title:"do-while",    desc:"Like while but always runs at least once."},
    ],
    filename:"loops.cpp",
    codeLines:[
      "#include <iostream>",
      "using namespace std;",
      "",
      "int main() {",
      "    // For loop",
      "    for (int i = 1; i <= 5; i++) {",
      "        cout << i << \" x 3 = \" << (i * 3) << endl;",
      "    }",
      "",
      "    // While loop",
      "    int count = 0;",
      "    while (count < 4) {",
      "        cout << \"Count: \" << count << endl;",
      "        count++;",
      "    }",
      "",
      "    // do-while — runs at least once",
      "    int n = 1;",
      "    do {",
      "        cout << \"n = \" << n << endl;",
      "        n *= 2;",
      "    } while (n < 20);",
      "",
      "    return 0;",
      "}",
    ],
    breakdown:[
      {token:"for (int i=1; i<=5; i++)", note:"Three parts: initialise (int i=1), condition (i<=5), step (i++). Identical to JavaScript."},
      {token:"count++",                  note:"Shorthand for count = count + 1. count-- subtracts 1."},
      {token:"do { … } while (n<20)",    note:"do-while runs the body FIRST, then checks the condition. Guarantees at least one run."},
    ],
    runnable:false, starterCode:"", challenges:[],
    mcqs:[
      {q:"What is unique about a do-while loop?",options:["It runs backwards","It always runs at least once","It doesn't need a condition","It runs forever"],answer:1},
      {q:"What does i++ do?",options:["Multiplies i by itself","Subtracts 1","Adds 1 to i","Resets i to 0"],answer:2},
      {q:"The for loop syntax in C++ is identical to which other language?",options:["Python","Ruby","JavaScript","Swift"],answer:2},
    ]
  },

  {
    id:"cpp5", title:"Functions", subtitle:"Reusable code with strict typing",
    intro:"C++ functions must declare their return type explicitly. This strictness lets the compiler optimise code and catch type errors before the program even runs.",
    concepts:[
      {icon:"🔧",title:"Return type", desc:"Declared before the function name: int add(…) returns an int."},
      {icon:"📥",title:"Parameters",  desc:"Must be typed: int add(int a, int b)"},
      {icon:"🚫",title:"void",        desc:"Return type when the function returns nothing."},
      {icon:"🔄",title:"Overloading", desc:"Same name, different parameter types — C++ picks the right version."},
    ],
    filename:"functions.cpp",
    codeLines:[
      "#include <iostream>",
      "#include <string>",
      "using namespace std;",
      "",
      "// void = returns nothing",
      "void greet(string name) {",
      '    cout << "Hello, " << name << "!" << endl;',
      "}",
      "",
      "// int = returns an integer",
      "int add(int a, int b) {",
      "    return a + b;",
      "}",
      "",
      "// double = returns a decimal",
      "double circleArea(double r) {",
      "    return 3.14159 * r * r;",
      "}",
      "",
      "int main() {",
      '    greet("Alice");',
      "    cout << add(5, 3)          << endl; // 8",
      "    cout << circleArea(5.0)    << endl; // 78.54",
      "    return 0;",
      "}",
    ],
    breakdown:[
      {token:"void greet(string name)",  note:"void = returns nothing. The function just does something (prints here)."},
      {token:"int add(int a, int b)",    note:"Return type (int) comes FIRST, then name, then typed parameters."},
      {token:"return a + b",             note:"Must return a value matching the declared return type. Compiler error if they mismatch."},
    ],
    runnable:false, starterCode:"", challenges:[],
    mcqs:[
      {q:"What return type means a function returns nothing?",options:["null","none","empty","void"],answer:3},
      {q:"In C++, where does the return type go?",options:["After the function name","Inside parentheses","Before the function name","At the end"],answer:2},
      {q:"What is function overloading?",options:["Calling too many times","Same name, different parameter types","A function inside another","Returning multiple values"],answer:1},
    ]
  },

  {
    id:"cpp6", title:"Arrays & Vectors", subtitle:"Collections of data in C++",
    intro:"C++ has two main ways to store lists: raw arrays (fixed size, very fast) and vectors (dynamic size, flexible). Modern C++ prefers vectors for almost everything.",
    concepts:[
      {icon:"📐",title:"Array",     desc:"Fixed-size list declared at compile time: int arr[5]"},
      {icon:"📋",title:"Vector",    desc:"Dynamic array from &lt;vector&gt; — resizes automatically."},
      {icon:"🔁",title:"Range for", desc:"Modern C++ loop: for (auto x : collection)"},
      {icon:"📊",title:".size()",   desc:"Returns the number of elements in a vector."},
    ],
    filename:"arrays.cpp",
    codeLines:[
      "#include <iostream>",
      "#include <vector>",
      "#include <string>",
      "using namespace std;",
      "",
      "int main() {",
      "    // Raw array (fixed size)",
      "    int scores[5] = {90, 85, 78, 92, 88};",
      "    cout << scores[0] << endl;  // 90",
      "",
      "    // Vector (dynamic, preferred)",
      '    vector<string> fruits = {"apple", "banana", "mango"};',
      "",
      '    fruits.push_back("kiwi");  // add to end',
      "    fruits.pop_back();          // remove last",
      "",
      "    cout << \"Size: \" << fruits.size() << endl;",
      "",
      "    // Range-based for loop (modern C++)",
      "    for (auto fruit : fruits) {",
      "        cout << fruit << endl;",
      "    }",
      "",
      "    // Classic indexed for loop",
      "    for (int i = 0; i < 5; i++) {",
      "        cout << scores[i] << \" \";",
      "    }",
      "    cout << endl;",
      "",
      "    return 0;",
      "}",
    ],
    breakdown:[
      {token:"int scores[5] = {…}",       note:"Raw array — must declare size upfront. Size is fixed and cannot change."},
      {token:"vector&lt;string&gt; fruits",note:"Vector stores items of ONE type (string here). Angle brackets specify the type."},
      {token:"fruits.push_back('kiwi')",   note:"push_back() adds to the end — like Python's .append() or JS's .push()."},
      {token:"for (auto fruit : fruits)",  note:"Range-based for loop — auto infers the variable type automatically."},
    ],
    runnable:false, starterCode:"", challenges:[],
    mcqs:[
      {q:"C++ equivalent of Python's list.append()?",options:["push()","append()","push_back()","add()"],answer:2},
      {q:"What makes vectors better than raw arrays?",options:["Faster","Can resize dynamically","Use less memory","No type required"],answer:1},
      {q:"What does 'auto' do in a range-based for loop?",options:["Creates a copy","Infers the variable type automatically","Runs in parallel","Skips null values"],answer:1},
    ]
  },
],

}; // end window.LESSONS
